import { CatalogItem } from './types';

export const INITIAL_CATALOG: CatalogItem[] = [
  {"id": "v_amla", "name": "Amla (Indian Gooseberry)", "category": "Vegetables", "units": ["lbs", "kg"], "emoji": "🫒"},
  {"id": "v_avo", "name": "Avocado", "category": "Vegetables", "units": ["pcs"], "emoji": "🥑"},
  {"id": "v_bell", "name": "Bell Peppers (Colorful)", "category": "Vegetables", "units": ["pcs", "lbs"], "emoji": "🫑"},
  {"id": "v_karela", "name": "Bitter Gourd (Karela)", "category": "Vegetables", "units": ["lbs", "kg"], "emoji": "🥒"},
  {"id": "v_lauki", "name": "Bottle Gourd (Lauki)", "category": "Vegetables", "units": ["pcs", "lbs"], "emoji": "🥒"},
  {"id": "v_cabbage", "name": "Cabbage (Patta Gobi)", "category": "Vegetables", "units": ["pcs", "head"], "emoji": "🥬"},
  {"id": "v_carrot", "name": "Carrots (Gajar)", "category": "Vegetables", "units": ["lbs", "bag", "kg"], "emoji": "🥕"},
  {"id": "v_cauli", "name": "Cauliflower (Gobi)", "category": "Vegetables", "units": ["pcs", "head"], "emoji": "🥦"},
  {"id": "v_coriander", "name": "Coriander (Dhaniya)", "category": "Vegetables", "units": ["bunch"], "emoji": "🌿"},
  {"id": "v_egg_big", "name": "Eggplant Big (Baingan)", "category": "Vegetables", "units": ["pcs", "lbs"], "emoji": "🍆"},
  {"id": "v_egg_small", "name": "Eggplant Small (Baingan)", "category": "Vegetables", "units": ["lbs", "kg"], "emoji": "🍆"},
  {"id": "v_methi", "name": "Fenugreek (Methi)", "category": "Vegetables", "units": ["bunch"], "emoji": "🌿"},
  {"id": "v_garlic", "name": "Garlic (Lahsun)", "category": "Vegetables", "units": ["pcs", "lbs", "mesh"], "emoji": "🧄"},
  {"id": "v_ginger", "name": "Ginger (Adrak)", "category": "Vegetables", "units": ["lbs", "gms", "inch"], "emoji": "🫚"},
  {"id": "v_chili", "name": "Green Chili (Hari Mirch)", "category": "Vegetables", "units": ["lbs", "gms"], "emoji": "🌶️"},
  {"id": "v_saag", "name": "Mustard Greens (Saag)", "category": "Vegetables", "units": ["bunch"], "emoji": "🥬"},
  {"id": "v_okra", "name": "Okra (Bhindi)", "category": "Vegetables", "units": ["lbs", "kg"], "emoji": "🌿"},
  {"id": "v_peas", "name": "Peas (Matar)", "category": "Vegetables", "units": ["lbs", "bag", "frozen pack"], "emoji": "🫛"},
  {"id": "v_pep_small", "name": "Peppers Small (Colorful)", "category": "Vegetables", "units": ["lbs", "bag"], "emoji": "🌶️"},
  {"id": "v_potato", "name": "Potatoes (Aloo)", "category": "Vegetables", "units": ["lbs", "bag", "kg"], "emoji": "🥔"},
  {"id": "v_radish", "name": "Radish (Mooli)", "category": "Vegetables", "units": ["bunch", "pcs"], "emoji": "🥕"},
  {"id": "v_onion", "name": "Red Onions (Pyaaz)", "category": "Vegetables", "units": ["lbs", "bag", "kg"], "emoji": "🧅"},
  {"id": "v_spinach", "name": "Spinach (Palak)", "category": "Vegetables", "units": ["bunch", "bag"], "emoji": "🍃"},
  {"id": "v_tomato", "name": "Tomatoes (Tamatar)", "category": "Vegetables", "units": ["lbs", "pcs", "kg"], "emoji": "🍅"},
  {"id": "f_banana", "name": "Banana (Kela)", "category": "Fruits", "units": ["doz", "bunch"], "emoji": "🍌"},
  {"id": "f_mango", "name": "Mango (Aam)", "category": "Fruits", "units": ["box", "pcs", "doz"], "emoji": "🥭"},
  {"id": "f_orange_l", "name": "Oranges Large", "category": "Fruits", "units": ["pcs", "lbs"], "emoji": "🍊"},
  {"id": "f_orange_s", "name": "Oranges Small", "category": "Fruits", "units": ["pcs", "lbs", "bag"], "emoji": "🍊"},
  {"id": "f_papaya", "name": "Papaya (Papita)", "category": "Fruits", "units": ["pcs"], "emoji": "🍈"},
  {"id": "f_pomegranate", "name": "Pomegranate (Anaar)", "category": "Fruits", "units": ["pcs", "lbs"], "emoji": "🍎"},
  {"id": "d_amul_block", "name": "Amul Cheese Block", "category": "Dairy", "units": ["block", "pkt"], "emoji": "🧀"},
  {"id": "d_amul_slice", "name": "Amul Cheese Slices", "category": "Dairy", "units": ["pkt"], "emoji": "🧀"},
  {"id": "d_butter", "name": "Butter (Makkhan)", "category": "Dairy", "units": ["stick", "box"], "emoji": "🧈"},
  {"id": "d_milk", "name": "Milk (Doodh)", "category": "Dairy", "units": ["gal", "pkt", "liter"], "emoji": "🥛"},
  {"id": "d_paneer", "name": "Paneer", "category": "Dairy", "units": ["block", "lbs", "pkt"], "emoji": "🧀"},
  {"id": "d_yogurt", "name": "Yogurt (Dahi)", "category": "Dairy", "units": ["tub", "cup"], "emoji": "🥣"},
  {"id": "p_rice", "name": "Basmati Rice (Chawal)", "category": "Pantry", "units": ["bag", "kg", "lbs"], "emoji": "🍚"},
  {"id": "p_oil", "name": "Cooking Oil (Tel)", "category": "Pantry", "units": ["can", "btl"], "emoji": "🛢️"},
  {"id": "p_dal", "name": "Lentils (Dal)", "category": "Pantry", "units": ["lbs", "kg", "pkt"], "emoji": "🥣"},
  {"id": "p_marie", "name": "Marie Biscuits", "category": "Pantry", "units": ["pkt", "roll"], "emoji": "🍪"},
  {"id": "p_toast", "name": "Toast Biscuits (Rusk)", "category": "Pantry", "units": ["pkt", "box"], "emoji": "🍞"},
  {"id": "p_atta", "name": "Wheat Flour (Atta)", "category": "Pantry", "units": ["bag", "kg", "lbs"], "emoji": "🌾"},
  {"id": "s_ajwain", "name": "Ajwain (Carom Seeds)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "🌿"},
  {"id": "s_amchur", "name": "Amchur (Dry Mango Pwd)", "category": "Spices", "units": ["pkt", "box"], "emoji": "🥭"},
  {"id": "s_anardana", "name": "Anardana (Pomegranate Seeds)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "🔴"},
  {"id": "s_badi_elaichi", "name": "Badi Elaichi (Black Cardamom)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "🟤"},
  {"id": "s_bayleaf", "name": "Bay Leaf (Tej Patta)", "category": "Spices", "units": ["pkt", "bunch"], "emoji": "🍃"},
  {"id": "s_black_pepper", "name": "Black Pepper (Kali Mirch)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "⚫"},
  {"id": "s_cinnamon", "name": "Cinnamon (Dalchini)", "category": "Spices", "units": ["sticks", "pkt"], "emoji": "🪵"},
  {"id": "s_cloves", "name": "Cloves (Laung)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "💮"},
  {"id": "s_coriander_pwd", "name": "Coriander Powder (Dhania)", "category": "Spices", "units": ["pkt", "box"], "emoji": "🌿"},
  {"id": "s_jeera", "name": "Cumin Seeds (Jeera)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "🟤"},
  {"id": "s_fennel", "name": "Fennel Seeds (Saunf)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "🟢"},
  {"id": "s_methi_seeds", "name": "Fenugreek Seeds (Methi)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "🟡"},
  {"id": "s_garam_masala", "name": "Garam Masala", "category": "Spices", "units": ["pkt", "box"], "emoji": "🥘"},
  {"id": "s_elaichi", "name": "Green Cardamom (Elaichi)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "🟢"},
  {"id": "s_hing", "name": "Hing (Asafoetida)", "category": "Spices", "units": ["btl", "box"], "emoji": "🧂"},
  {"id": "s_javitri", "name": "Mace (Javitri)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "🟠"},
  {"id": "s_mustard_seeds", "name": "Mustard Seeds (Rai)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "⚫"},
  {"id": "s_nigella", "name": "Nigella Seeds (Kalonji)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "⚫"},
  {"id": "s_nutmeg", "name": "Nutmeg (Jaiphal)", "category": "Spices", "units": ["pcs", "pkt"], "emoji": "🟤"},
  {"id": "s_chili_pwd", "name": "Red Chili Powder (Laal Mirch)", "category": "Spices", "units": ["pkt", "box"], "emoji": "🌶️"},
  {"id": "s_saffron", "name": "Saffron (Kesar)", "category": "Spices", "units": ["gm", "box"], "emoji": "🌸"},
  {"id": "s_sesame", "name": "Sesame Seeds (Til)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "⚪"},
  {"id": "s_star_anise", "name": "Star Anise (Chakra Phool)", "category": "Spices", "units": ["pkt", "pcs"], "emoji": "⭐"},
  {"id": "s_haldi", "name": "Turmeric (Haldi)", "category": "Spices", "units": ["pkt", "gms"], "emoji": "🟡"}
];